//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctoAwesome.Client.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OctoKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OctoKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OctoAwesome.Client.Languages.OctoKeys", typeof(OctoKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Backward.
        /// </summary>
        internal static string backward {
            get {
                return ResourceManager.GetString("backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBUG: All Blocktypes in Inventory.
        /// </summary>
        internal static string debug_allblocks {
            get {
                return ResourceManager.GetString("debug_allblocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBUG: Show/Hide Debug Control.
        /// </summary>
        internal static string debug_control {
            get {
                return ResourceManager.GetString("debug_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flymode.
        /// </summary>
        internal static string flymode {
            get {
                return ResourceManager.GetString("flymode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Forward.
        /// </summary>
        internal static string forward {
            get {
                return ResourceManager.GetString("forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free/Capture Mouse.
        /// </summary>
        internal static string freemouse {
            get {
                return ResourceManager.GetString("freemouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Full Screen Mode.
        /// </summary>
        internal static string fullscreen {
            get {
                return ResourceManager.GetString("fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Down.
        /// </summary>
        internal static string headdown {
            get {
                return ResourceManager.GetString("headdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Left.
        /// </summary>
        internal static string headleft {
            get {
                return ResourceManager.GetString("headleft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Right.
        /// </summary>
        internal static string headright {
            get {
                return ResourceManager.GetString("headright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Up.
        /// </summary>
        internal static string headup {
            get {
                return ResourceManager.GetString("headup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide all Controls.
        /// </summary>
        internal static string hidecontrols {
            get {
                return ResourceManager.GetString("hidecontrols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interact.
        /// </summary>
        internal static string interact {
            get {
                return ResourceManager.GetString("interact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string inventory {
            get {
                return ResourceManager.GetString("inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump.
        /// </summary>
        internal static string jump {
            get {
                return ResourceManager.GetString("jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Left.
        /// </summary>
        internal static string left {
            get {
                return ResourceManager.GetString("left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Right.
        /// </summary>
        internal static string right {
            get {
                return ResourceManager.GetString("right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Slot 0.
        /// </summary>
        internal static string slot0 {
            get {
                return ResourceManager.GetString("slot0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Slot 1.
        /// </summary>
        internal static string slot1 {
            get {
                return ResourceManager.GetString("slot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Slot 2.
        /// </summary>
        internal static string slot2 {
            get {
                return ResourceManager.GetString("slot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Slot 3.
        /// </summary>
        internal static string slot3 {
            get {
                return ResourceManager.GetString("slot3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Slot 4.
        /// </summary>
        internal static string slot4 {
            get {
                return ResourceManager.GetString("slot4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Slot 5.
        /// </summary>
        internal static string slot5 {
            get {
                return ResourceManager.GetString("slot5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Slot 6.
        /// </summary>
        internal static string slot6 {
            get {
                return ResourceManager.GetString("slot6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Slot 7.
        /// </summary>
        internal static string slot7 {
            get {
                return ResourceManager.GetString("slot7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Slot 8.
        /// </summary>
        internal static string slot8 {
            get {
                return ResourceManager.GetString("slot8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Slot 9.
        /// </summary>
        internal static string slot9 {
            get {
                return ResourceManager.GetString("slot9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport.
        /// </summary>
        internal static string teleport {
            get {
                return ResourceManager.GetString("teleport", resourceCulture);
            }
        }
    }
}
